FROM golang:1.18.0-alpine3.15 as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash

ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn,direct

COPY ./go.mod /app/go.mod
COPY ./go.sum /app/go.sum

COPY ./mt-bindings /app/mt-bindings

WORKDIR /app/mt-node
RUN go mod download -x

COPY ./mt-node /app/mt-node

RUN go build -o ./bin/stateviz ./cmd/stateviz

FROM alpine:3.15

COPY --from=builder /app/mt-node/bin/stateviz /usr/local/bin

CMD ["stateviz"]
