// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: sequencer.proto

package sequencer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SequencerClient is the client API for Sequencer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SequencerClient interface {
	PostBlock(ctx context.Context, in *PostBlockRequest, opts ...grpc.CallOption) (*PostBlockReply, error)
}

type sequencerClient struct {
	cc grpc.ClientConnInterface
}

func NewSequencerClient(cc grpc.ClientConnInterface) SequencerClient {
	return &sequencerClient{cc}
}

func (c *sequencerClient) PostBlock(ctx context.Context, in *PostBlockRequest, opts ...grpc.CallOption) (*PostBlockReply, error) {
	out := new(PostBlockReply)
	err := c.cc.Invoke(ctx, "/sequencer.Sequencer/PostBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SequencerServer is the server API for Sequencer service.
// All implementations must embed UnimplementedSequencerServer
// for forward compatibility
type SequencerServer interface {
	PostBlock(context.Context, *PostBlockRequest) (*PostBlockReply, error)
	mustEmbedUnimplementedSequencerServer()
}

// UnimplementedSequencerServer must be embedded to have forward compatible implementations.
type UnimplementedSequencerServer struct {
}

func (UnimplementedSequencerServer) PostBlock(context.Context, *PostBlockRequest) (*PostBlockReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostBlock not implemented")
}
func (UnimplementedSequencerServer) mustEmbedUnimplementedSequencerServer() {}

// UnsafeSequencerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SequencerServer will
// result in compilation errors.
type UnsafeSequencerServer interface {
	mustEmbedUnimplementedSequencerServer()
}

func RegisterSequencerServer(s grpc.ServiceRegistrar, srv SequencerServer) {
	s.RegisterService(&Sequencer_ServiceDesc, srv)
}

func _Sequencer_PostBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequencerServer).PostBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sequencer.Sequencer/PostBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequencerServer).PostBlock(ctx, req.(*PostBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sequencer_ServiceDesc is the grpc.ServiceDesc for Sequencer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sequencer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sequencer.Sequencer",
	HandlerType: (*SequencerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostBlock",
			Handler:    _Sequencer_PostBlock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sequencer.proto",
}
