
networks:
  mantle:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

x-healthcheck: &healthcheck
  test: [ "CMD", "curl", "-sf", "http://localhost:8545" ]
  interval: 5s
  timeout: 5s
  retries: 3
  start_period: 30s


services:
  l2geth:
#    depends_on:
#      - dtl
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    # override with the geth script and the env vars required for it
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    volumes:
      - ./data/l2geth:/root/.ethereum/geth/
    container_name: bitl2geth
    environment:
      ETH1_HTTP: http://10.0.0.2:8545
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://10.0.0.3:8081/state-dump.latest.json
      # connecting to the DTL
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      VERBOSITY: 3
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: '6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27'
      BLOCK_SIGNER_ADDRESS: '0x00000398232E2064F896018496b4b44b3D62751F'

      ROLLUP_ENFORCE_FEES: ${ROLLUP_ENFORCE_FEES:-false}
      ROLLUP_FEE_THRESHOLD_DOWN: 0.9
      ROLLUP_FEE_THRESHOLD_UP: 1.1

      GASPRICE: 0
    ports:
      - ${L2GETH_HTTP_PORT:-8545}:8545
      - ${L2GETH_WS_PORT:-8546}:8546
    healthcheck: *healthcheck
    networks:
      mantle:
        ipv4_address: 10.0.0.7


  verifier:
    depends_on:
#      - dtl
      - l2geth
    # deploy:
    #   replicas: 1
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    container_name: bitverifier
    env_file:
      - ./envs/geth.env
    volumes:
      - ./data/verifier:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: http://10.0.0.2:8545
      SEQUENCER_CLIENT_HTTP: http://l2geth:8545
      ROLLUP_STATE_DUMP_PATH: http://10.0.0.3:8081/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ROLLUP_BACKEND: 'l1'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      VERBOSITY: 3
      ROLLUP_VERIFIER_ENABLE: 'true'
    ports:
      - ${VERIFIER_HTTP_PORT:-8547}:8545
      - ${VERIFIER_WS_PORT:-8548}:8546
    networks:
      mantle: {}

  replica:
    depends_on:
#      - dtl
      - l2geth
    # deploy:
    #   replicas: 1
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    container_name: bitreplica
    env_file:
      - ./envs/geth.env
    environment:
      ETH1_HTTP: http://10.0.0.2:8545
      SEQUENCER_CLIENT_HTTP: http://l2geth:8545
      ROLLUP_STATE_DUMP_PATH: http://10.0.0.3:8081/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ROLLUP_BACKEND: 'l2'
      ROLLUP_VERIFIER_ENABLE: 'true'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      VERBOSITY: 3
    ports:
      - ${REPLICA_HTTP_PORT:-8549}:8545
      - ${REPLICA_WS_PORT:-8550}:8546
    networks:
      mantle: {}

